# -*- coding: utf-8 -*-
"""Desafio_Citi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cI52t3Y7Z1RCJsqe054cWSQiopTPwhJI
"""

import pandas as pd
import numpy as np
import re

df = pd.read_csv('/Base_Financeira_PTC_26.csv')
print("✅ Ficheiro carregado com sucesso! Iniciando tratamento...")

df.columns = df.columns.str.strip()

df = df.dropna(how='all')

df = df.drop_duplicates()

def formatar_cpf(cpf):
    if pd.isna(cpf) or str(cpf).strip() == '': return "Não informado"
    num = re.sub(r'\D', '', str(cpf))
    if len(num) == 11:
        return f"{num[:3]}.{num[3:6]}.{num[6:9]}-{num[9:]}"
    return "Não informado"
df['CPF_Cliente'] = df['CPF_Cliente'].apply(formatar_cpf)

df['Data_Transacao'] = pd.to_datetime(df['Data_Transacao'], dayfirst=True, errors='coerce').dt.strftime('%Y-%m-%d')

taxas = {'USD': 5.00, 'EUR': 5.50, 'GBP': 6.30, 'BRL': 1.00}
df['Valor_Transacao'] = df['Valor_Transacao'].astype(str).str.replace(r'[R$\s]', '', regex=True).str.replace(',', '.')
df['Valor_Transacao'] = pd.to_numeric(df['Valor_Transacao'], errors='coerce')

df.loc[(df['Valor_Transacao'] <= 0) | (df['Valor_Transacao'] > 1000000), 'Valor_Transacao'] = np.nan
df['Valor_Transacao'] = df['Valor_Transacao'].fillna(df['Valor_Transacao'].median())

df['Moeda'] = df['Moeda'].str.strip().str.upper()
df['Valor_Transacao'] = df.apply(lambda r: r['Valor_Transacao'] * taxas.get(r['Moeda'], 1), axis=1)
df['Moeda'] = 'BRL'

mapa_tipo = {
    'ted': 'Transferência', 'doc': 'Transferência', 'transf.': 'Transferência', 'transferencia': 'Transferência',
    'boleto': 'Pagamento', 'pgto.': 'Pagamento', 'pagamento': 'Pagamento',
    'resgate': 'Saque', 'saque': 'Saque', 'pix': 'PIX', 'p-i-x': 'PIX', 'depósito': 'Depósito', 'deposito': 'Depósito'
}
df['Tipo_Transacao'] = df['Tipo_Transacao'].astype(str).str.lower().str.strip().map(mapa_tipo)
df['Tipo_Transacao'] = df['Tipo_Transacao'].fillna(df['Tipo_Transacao'].mode()[0])

mapa_status = {
    'aprovada': 'Aprovada', 'autorizada': 'Aprovada', 'negada': 'Recusada',
    'recusada': 'Recusada', 'bloqueada': 'Recusada', 'pendente': 'Pendente',
    'em processamento': 'Pendente', 'aguardando': 'Pendente'
}
df['Status_Transacao'] = df['Status_Transacao'].astype(str).str.lower().str.strip().map(mapa_status)

df['Nome_Cliente'] = df['Nome_Cliente'].astype(str).str.replace('_', ' ').str.strip().str.title()

df['Num_Parcelas'] = df['Num_Parcelas'].astype(str).apply(lambda x: re.sub(r'\D', '', x))
df['Num_Parcelas'] = pd.to_numeric(df['Num_Parcelas']).fillna(1).astype(int)

df['Taxa_Servico'] = pd.to_numeric(df['Taxa_Servico'], errors='coerce').abs()
df['Taxa_Servico'] = df['Taxa_Servico'].fillna(df['Taxa_Servico'].mean())

df['Valor_Final'] = pd.to_numeric(df['Valor_Final'], errors='coerce')
invalido = (df['Valor_Final'] < df['Valor_Transacao']) | (df['Valor_Final'].isna())
df.loc[invalido, 'Valor_Final'] = df['Valor_Transacao'] + df['Taxa_Servico']

df.to_csv('Base_Tratada_Final.csv', index=False)
print("✅ Etapa 1 100% concluída! Arquivo 'Base_Tratada_Final.csv' foi gerado e está pronto.")

# Instalar a nova biblioteca oficial do Google
!pip install -q -U google-genai
from google import genai
from google.colab import userdata

try:
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    client = genai.Client(api_key=GOOGLE_API_KEY)
except Exception as e:
    print("ERRO: Ocorreu um problema com a chave. Verifica se ativaste o botão azul no Secret 'GOOGLE_API_KEY'!")

resumo = f"""
RESUMO ANALÍTICO DAS TRANSAÇÕES:
- Total: {len(df)} transações.
- Volume Total: R$ {df['Valor_Transacao'].sum():,.2f}
- Status: {df['Status_Transacao'].value_counts().to_dict()}
- Tipos mais usados: {df['Tipo_Transacao'].value_counts().head(3).to_dict()}
- Ticket Médio por Tipo: {df.groupby('Tipo_Transacao')['Valor_Transacao'].mean().to_dict()}
- Top Clientes com Recusas: {df[df['Status_Transacao']=='Recusada']['Nome_Cliente'].value_counts().head(3).to_dict()}
"""

print("\n---  Assistente Financeiro Citi Ativo ---")
while True:
    pergunta = input("\nPergunta (ou digite 'sair'): ")
    if pergunta.lower() == 'sair':
        print("Assistente encerrado.")
        break

    prompt = f"És um analista de dados sênior do Citi. Com base unicamente nestes dados tratados: {resumo}. Responde de forma clara, profissional e direta à pergunta: {pergunta}"

    try:
        resposta = client.models.generate_content(
            model='gemini-2.0-flash',
            contents=prompt
        )
        print(f"\nANÁLISE: {resposta.text}")
        print("-" * 40)
    except Exception as e:
        print(f"\nErro ao gerar resposta: {e}")

!pip install -q -U google-generativeai
import google.generativeai as genai
from google.colab import userdata

GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')